name: Docker CI

on: [push, pull_request]

# on:
#   push:
#     branches: [ master ]
#     tags:
#       - v*
#   pull_request:
#     branches: [ master ]

jobs:

  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: make docker/build

    - name: Build the Docker image
      run: make docker/tag TAG_NAME=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_TOKEN }}

    - name: Push the Docker image
      run: make docker/push

  build-and-publish-branch:
    runs-on: ubuntu-latest
    if: github.head_ref != '' # Run this on PRS

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: make docker/build

    - name: Build the Docker image
      run: make docker/tag TAG_NAME=${{ github.head_ref }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_TOKEN }}

    - name: Push the Docker image
      run: make docker/push

